### ISSUE TITLE
add post-norm configuration with deepnet init

### ISSUE THREAD

**Issue by lucidrains** [lucidrains/RETRO-pytorch#8]
https://arxiv.org/abs/2203.00555

**Comment by lucidrains** [comment]
just need the init(retro) function now https://github.com/lucidrains/RETRO-pytorch/commit/1c57013fd377d01781f35321f4825f763ca25255

**Comment by lucidrains** [comment]
made the residual scaling customizable because with the cross attention in RETRO being every 3rd layer, it may end up being different than what is in the paper

**Comment by lucidrains** [comment]
done

**Comment by OhadRubin** [comment]
Hey @lucidrains,
I'm trying to replicate RETRO in Jax, and it isn't going well.
How crucial was the deepnet init to convergence?
Because right now, my model can't even solve a very simple task.
(The task is reversing a string that is encrypted using a simple cypher, where the cypher is given as the neighbor tokens, so a model without cca can't solve it).
